export const API_CONFIG = {
  BASE_URL: process.env.EXPO_PUBLIC_API_URL || 'http://192.168.8.194:5000/api',
  TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
};

export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_OTP: '/auth/verify-otp',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH_TOKEN: '/auth/refresh',
    LOGOUT: '/auth/logout',
    GOOGLE_LOGIN: '/auth/google',
    CURRENT_USER: '/auth/me',
  },
  DOCTORS: {
    LIST: '/doctors',
    DETAIL: (id: string) => `/doctors/${id}`,
    SEARCH: '/doctors/search',
    BY_SPECIALTY: (specialty: string) => `/doctors/specialty/${specialty}`,
    AVAILABLE_SLOTS: (id: string, date: string) => `/doctors/${id}/slots?date=${date}`,
  },
  APPOINTMENTS: {
    LIST: '/appointments',
    DETAIL: (id: string) => `/appointments/${id}`,
    CREATE: '/appointments',
    UPDATE: (id: string) => `/appointments/${id}`,
    CANCEL: (id: string) => `/appointments/${id}/cancel`,
    DELETE: (id: string) => `/appointments/${id}`,
  },
  MEDICAL_RECORDS: {
    FOLDERS: '/medical-records/folders',
    FOLDER_DETAIL: (id: string) => `/medical-records/folders/${id}`,
    RECORDS: '/medical-records',
    RECORD_DETAIL: (id: string) => `/medical-records/${id}`,
    RECORDS_BY_FOLDER: (folderId: string) => `/medical-records/folders/${folderId}/records`,
    CREATE: '/medical-records',
    UPDATE: (id: string) => `/medical-records/${id}`,
    DELETE: (id: string) => `/medical-records/${id}`,
    SEARCH: '/medical-records/search',
  },
  JENDO_TESTS: {
    LIST: '/jendo-tests',
    DETAIL: (id: string) => `/jendo-tests/${id}`,
    LATEST: '/jendo-tests/latest',
    BY_RISK_LEVEL: (level: string) => `/jendo-tests/risk-level/${level}`,
    CREATE: '/jendo-tests',
    SEARCH: '/jendo-tests/search',
  },
  WELLNESS: {
    TIPS: '/wellness/tips',
    TIP_DETAIL: (id: string) => `/wellness/tips/${id}`,
    TIPS_BY_CATEGORY: (category: string) => `/wellness/tips/category/${category}`,
    LEARNING_MATERIALS: '/learning-materials',
    LEARNING_MATERIAL_DETAIL: (id: string) => `/learning-materials/${id}`,
    LEARNING_BY_CATEGORY: (category: string) => `/learning-materials/category/${category}`,
    LEARNING_SEARCH: (query: string) => `/learning-materials/search?query=${query}`,
    FEATURED_MATERIALS: '/wellness/learning/featured',
    RECOMMENDATIONS: '/wellness/recommendations',
    CHAT: '/wellness/chat',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD: '/notifications/unread',
    UNREAD_COUNT: '/notifications/unread/count',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE: (id: string) => `/notifications/${id}`,
    BY_TYPE: (type: string) => `/notifications/type/${type}`,
    PREFERENCES: '/notifications/preferences',
  },
  DASHBOARD: {
    DATA: '/dashboard',
    STATISTICS: '/dashboard/statistics',
    QUICK_ACTIONS: '/dashboard/quick-actions',
  },
  USER: {
    PROFILE: '/user/profile',
    UPDATE_PROFILE: '/user/profile',
    HEALTH_PARAMETERS: '/user/health-parameters',
    CHANGE_PASSWORD: '/user/change-password',
    UPLOAD_IMAGE: '/user/profile-image',
    DELETE_ACCOUNT: '/user/delete',
    HEALTH_SUMMARY: '/user/health-summary',
  },
};
